Use OpenGL renderer
For installation see https://forum.processing.org/one/topic/mac-osx-10-8-3-opengl-noclassdeffounderror-javax-media-opengl-glexception.html.

As it turned out, the OpenGL .jar files from Resources/Java/core/library just needed to be copied to the folder /System/Library/Java/Extensions. In my case, this worked after copying the following:
jogl-all.jar
jogl-all-natives-macosx-universal.jar
gluegen-rt.jar
gluegen-rt-natives-macosx-universal.jar